# Generated by Django 3.0.2 on 2020-07-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_Country', models.IntegerField(primary_key=True, serialize=False)),
                ('name_Country', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_Customer', models.IntegerField(primary_key=True, serialize=False)),
                ('name_Customer', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('phone_Number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_News', models.IntegerField(primary_key=True, serialize=False)),
                ('titlle', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_Tour',
            fields=[
                ('id_Type', models.IntegerField(primary_key=True, serialize=False)),
                ('name_Type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_User', models.IntegerField(primary_key=True, serialize=False)),
                ('name_User', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('permission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_Tour', models.IntegerField(primary_key=True, serialize=False)),
                ('name_Tour', models.CharField(max_length=256)),
                ('price_Tour', models.IntegerField()),
                ('date_Start', models.DateField(auto_now_add=True)),
                ('origin_Place', models.CharField(max_length=256)),
                ('image_Tour', models.ImageField(upload_to='')),
                ('type_Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Type_Tour')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Order', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Toal_Money', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Customer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='Information_Guess',
            fields=[
                ('id_Guess', models.IntegerField(primary_key=True, serialize=False)),
                ('name_Guess', models.CharField(max_length=256)),
                ('sex', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Customer')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='Image_of_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Tour', models.ImageField(upload_to='')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Tour')),
            ],
        ),
        migrations.CreateModel(
            name='Image_of_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.News')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_City', models.IntegerField(primary_key=True, serialize=False)),
                ('name_City', models.CharField(max_length=256)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Country')),
            ],
        ),
    ]
