# Generated by Django 3.0.2 on 2020-07-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Through',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.City')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selltour.Tour')),
            ],
            options={
                'unique_together': {('tour', 'city')},
            },
        ),
    ]
