# Generated by Django 3.0.2 on 2020-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0005_auto_20200707_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='last',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image_of_news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image_of_tour',
            name='image_Tour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_Tour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
