# Generated by Django 3.0.2 on 2020-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0006_auto_20200707_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date_Start',
            field=models.DateField(),
        ),
    ]
