# Generated by Django 2.2.14 on 2020-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0007_auto_20200707_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
