# Generated by Django 2.2.14 on 2020-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0008_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tour',
            name='Date_Order',
            field=models.DateField(auto_now_add=True),
        ),
    ]
