# Generated by Django 2.2.14 on 2020-07-15 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0009_auto_20200712_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_guess',
            name='age',
        ),
        migrations.AddField(
            model_name='information_guess',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
