# Generated by Django 2.2.14 on 2020-07-17 08:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selltour', '0010_auto_20200715_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
